### ISSUE TITLE
-DBLE_SUPPORT=OFF causes errors

### ISSUE THREAD

**Issue by hongkongkiwi** [infsoft-locaware/nrfdfu#5]
When turning bluetooth off, I get the following compile error:
main.c:(.text.startup+0x6b8): undefined reference to `ble_wait_disconnect'

**Comment by hongkongkiwi** [comment]
Added pull request in #6

**Comment by br101** [comment]
i think your pull request is largely unnecessary, please check with the fix i just commited now

**Comment by hongkongkiwi** [comment]
Thanks, that seems to do the trick for compilation now.
